volumes:
  go-logging:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - go-logging:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_USERNAME=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}


  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    volumes:
      - go-logging:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USER}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch

#  go-logging:
#    image: go-logging:local
#    container_name: go-logging
#    restart: always
#    build:
#      context: .
#      dockerfile: /app/Dockerfile
#    volumes:
#      - go-logging:/go-logging
#    depends_on:
#      - elasticsearch
